services:
    nginx:
        image: nginx:alpine
        container_name: video-streamer
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certs:/etc/letsencrypt
            - ./certs-data:/data/letsencrypt
        restart: always
        depends_on:
            - certbot

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certs:/etc/letsencrypt
            - ./certs-data:/data/letsencrypt
        entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 1 & wait $!; done'
