services:
    vite-app:
        image: nginx:alpine
        container_name: video-streamer
        ports:
            - "80:80"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
